### ISSUE TITLE
Navbar issue

### ISSUE THREAD

**Issue by surajmandalcell** [therdas/therdas.github.io#3] opened 2017-10-07 19:33 UTC
To reproduce 👍
1. Open the site 
2. Scroll down
3. then scroll up a little

![image](https://user-images.githubusercontent.com/11650177/31311163-f3f861d6-abc3-11e7-9b40-dea2c7954eae.png)

-----
Browser : Firefox 57 beta 6
Os : Windows 7
P.s. : lol

**Comment by therdas** [comment] 2017-10-08 05:16
Probably a firefox bug, cannot reproduce in chrome

**Comment by therdas** [comment] 2017-10-08 05:19
Reproduced in firefox, doesn't properly calculate auto margins on reapplying styles

**Comment by therdas** [comment] 2017-10-08 07:41
Yep, was a firefox problem with flex-box and fixed align-self:center elements, fixed by removing from flexbox flow and manually centering with %ages. Fix should be up soon (Internet problems)

**Closed by therdas** 2017-10-08 07:41 UTC
